# Generated by Django 2.2.3 on 2020-02-12 08:17

import cloudform.user_domain.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomain",
            name="allow_change_ldap_password",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="approver_search_filter_str",
            field=models.CharField(default="(mail=%(user)s)", max_length=255),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="bind_dn",
            field=models.CharField(default="<please set the value>", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="bind_password",
            field=models.CharField(default="<please set the value>", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="default_group",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="display_name",
            field=models.CharField(default="<please set the value>", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="flags_by_group",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=cloudform.user_domain.models.default_flags_by_group
            ),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="group_map",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=cloudform.user_domain.models.default_group_map
            ),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="group_search_base_dn",
            field=models.CharField(default="DC=pttdigital,DC=corp", max_length=255),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="group_search_filter_str",
            field=models.CharField(
                default="(objectClass=group)",
                max_length=255,
                verbose_name="Group search filter",
            ),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="mirror_groups_except",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=cloudform.user_domain.models.default_mirror_groups_except,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="server_uri",
            field=models.CharField(default="<please set the value>", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="start_tls",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="user_attr_map",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=cloudform.user_domain.models.default_user_attr_map
            ),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="user_search_base_dn",
            field=models.CharField(default="<please set the value>", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdomain",
            name="user_search_filter_str",
            field=models.CharField(
                default="<please set the value>",
                max_length=255,
                verbose_name="User search filter",
            ),
            preserve_default=False,
        ),
    ]
