# Generated by Django 2.2.3 on 2020-02-17 11:32

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_domain", "0003_auto_20200212_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="bind_password",
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
