# Generated by Django 2.2.3 on 2020-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_domain', '0004_auto_20200217_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdomain',
            name='reviewer_search_filter_str',
            field=models.CharField(default='(mail=%(user)s)', max_length=255),
        ),
    ]
