# Generated by Django 2.2.3 on 2021-12-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20211213_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='active_flag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_by',
        ),
    ]
