# Generated by Django 3.0.3 on 2020-02-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
