# Generated by Django 2.2.3 on 2019-12-11 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="LocalUser",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("users.user",),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                default="blank@thezouth.com",
                max_length=255,
                validators=[django.core.validators.EmailValidator],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
