# Generated by Django 2.2.3 on 2019-12-15 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_fields_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
            ],
            options={
                'verbose_name': 'PTT User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterModelOptions(
            name='localuser',
            options={'verbose_name': 'Non-PTT User'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
