# Generated by Django 2.2.4 on 2019-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sequence", "0001_initial")]

    operations = [
        migrations.RemoveConstraint(model_name="sequence", name="unique_sequence"),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(
                fields=("name", "prefix"), name="unique_sequence"
            ),
        ),
    ]
