# Generated by Django 2.2.3 on 2020-09-24 05:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('data_center', models.CharField(max_length=255)),
                ('application_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('job_code', models.CharField(max_length=255)),
                ('price_detail', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
