# Generated by Django 2.2.3 on 2020-09-28 09:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
