# Generated by Django 2.2.3 on 2020-09-28 09:52

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20200928_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
