# Generated by Django 2.2.3 on 2020-09-30 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20200928_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='power_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
