# Generated by Django 2.2.3 on 2020-10-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20201001_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='price_detail',
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_price',
            field=models.DecimalField(decimal_places=6, max_digits=19, null=True),
        ),
        migrations.CreateModel(
            name='PriceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('unit', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=19, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.Inventory')),
            ],
        ),
    ]
