# Generated by Django 2.2.3 on 2020-10-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_auto_20201002_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedetail',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_detail', to='inventories.Inventory'),
        ),
    ]
