# Generated by Django 2.2.3 on 2020-10-07 12:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0007_auto_20201002_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('secondary_name', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=30)),
                ('data_center', models.CharField(max_length=255)),
                ('job_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
