# Generated by Django 2.2.3 on 2020-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_inventorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='project',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
