# Generated by Django 2.2.3 on 2020-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_inventorylist_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='resource_type',
            field=models.CharField(choices=[('vm', 'Virtual machine'), ('container-cluster', 'Openshift project')], max_length=30),
        ),
    ]
