# Generated by Django 2.2.3 on 2020-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_auto_20201031_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='resource_type',
            field=models.CharField(choices=[('vm', 'Virtual machine'), ('container-cluster', 'Openshift project')], max_length=30, null=True),
        ),
    ]
