# Generated by Django 2.2.3 on 2020-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0011_inventory_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='power_state_point',
            field=models.IntegerField(null=True),
        ),
    ]
