# Generated by Django 2.2.3 on 2020-12-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0012_inventory_power_state_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylist',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
