# Generated by Django 2.2.3 on 2021-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0013_auto_20201220_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='vm_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
