# Generated by Django 2.2.3 on 2021-01-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0014_inventory_vm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='vm_id',
        ),
        migrations.AddField(
            model_name='inventorylist',
            name='vm_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
