# Generated by Django 2.2.3 on 2021-01-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0015_auto_20210101_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='number_of_checking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
