# Generated by Django 2.2.3 on 2021-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0016_inventorylist_number_of_checking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='number_of_checking',
            field=models.IntegerField(default=0),
        ),
    ]
