# Generated by Django 2.2.3 on 2021-01-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0017_auto_20210115_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='recheck',
            field=models.BooleanField(default=False),
        ),
    ]
