# Generated by Django 2.2.3 on 2021-02-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210217_1541'),
        ('inventories', '0018_inventorylist_recheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='data_center_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_center', to='projects.DataCenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorylist',
            name='data_center',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
