# Generated by Django 2.2.3 on 2021-02-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0019_auto_20210219_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylist',
            name='data_center',
        ),
    ]
