# Generated by Django 2.2.3 on 2021-05-16 13:48

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0021_auto_20210221_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryListLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_list_id', models.CharField(blank=True, max_length=255, null=True)),
                ('before', models.CharField(blank=True, max_length=255, null=True)),
                ('after', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log Inventory List',
                'verbose_name_plural': 'Audit Log Inventory List',
            },
        ),
    ]
