# Generated by Django 2.2.3 on 2021-08-01 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0022_inventorylistlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 5, 29, 8, 615471)),
        ),
    ]
