# Generated by Django 2.2.3 on 2021-12-13 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0023_auto_20210801_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 15, 3, 35, 644921)),
        ),
    ]
