# Generated by Django 2.2.3 on 2021-12-19 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20211213_1456'),
        ('inventories', '0024_auto_20211213_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 10, 17, 1, 393725)),
        ),
    ]
