# Generated by Django 2.2.3 on 2021-12-19 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0025_auto_20211219_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 10, 19, 49, 466010)),
        ),
        migrations.AlterField(
            model_name='inventorylist',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag'),
        ),
    ]
