# Generated by Django 2.2.3 on 2021-12-20 15:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0026_auto_20211219_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 15, 33, 0, 214187)),
        ),
    ]
