# Generated by Django 2.2.3 on 2021-12-26 09:56

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0027_auto_20211220_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 9, 56, 11, 373272)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
