# Generated by Django 2.2.3 on 2022-07-07 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0028_auto_20211226_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 14, 55, 27, 590068)),
        ),
    ]
