# Generated by Django 2.2.3 on 2019-12-10 09:14

import cloudform.projects.models.data_center
import cloudform.projects.models.project
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                ("supporter_name", models.CharField(max_length=255)),
                ("supporter_email", models.CharField(max_length=255)),
                (
                    "supporter_department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("supporter_organization", models.CharField(max_length=255)),
                ("system_diagram", models.FileField(blank=True, upload_to="")),
            ],
            options={"abstract": False},
            bases=(cloudform.projects.models.project.ProjectChildMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AppRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("relation", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DataCenter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "data center",
                "verbose_name_plural": "data centers",
            },
            managers=[
                ("objects", cloudform.projects.models.data_center.DataCenterManager())
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("job_code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("expired_date", models.DateTimeField()),
                ("go_live_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("resource_type", models.CharField(max_length=30)),
                ("job_code", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(null=True)),
                (
                    "details",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInventory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "service inventory",
                "verbose_name_plural": "service inventories",
                "abstract": False,
            },
        ),
    ]
