# Generated by Django 2.2.3 on 2020-01-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_audit_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='default_job_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='tenant',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
