# Generated by Django 2.2.3 on 2020-01-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_additional_attrs_for_data_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='secondary_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
