# Generated by Django 2.2.3 on 2020-01-21 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_resource_secondary_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacenter",
            name="available_resources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=["vm", "other"],
                size=None,
                verbose_name="Available Resource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datacenter",
            name="default_job_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
