# Generated by Django 2.2.3 on 2020-01-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20200121_0723"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceinventory",
            name="description",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
