# Generated by Django 2.2.3 on 2020-02-04 07:43

import cloudform.projects.models.application
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0006_serviceinventory_description")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="projects.Project",
                validators=[cloudform.projects.models.application.validate_only_active],
            ),
        )
    ]
