# Generated by Django 2.2.3 on 2020-09-04 07:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_valid_project_validation_on_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataCenter')),
            ],
            options={
                'unique_together': {('data_center', 'level')},
            },
        ),
    ]
