# Generated by Django 2.2.3 on 2020-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_datacenterlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ['name'], 'verbose_name': 'data center', 'verbose_name_plural': 'data centers'},
        ),
        migrations.AlterModelOptions(
            name='datacenterlevel',
            options={'ordering': ['data_center']},
        ),
    ]
