# Generated by Django 2.2.3 on 2021-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_20201127_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
