# Generated by Django 2.2.3 on 2021-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210217_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='endpoint',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
