# Generated by Django 2.2.3 on 2021-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210217_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacenter',
            old_name='endpoint',
            new_name='endpoint_openshif',
        ),
        migrations.AddField(
            model_name='datacenter',
            name='endpoint_vm',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
