# Generated by Django 2.2.3 on 2021-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210217_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='endpoint_openshif',
            field=models.URLField(blank=True, help_text='This field use for Billing only', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='endpoint_vm',
            field=models.URLField(blank=True, help_text='This field use for Billing only', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='password',
            field=models.CharField(blank=True, help_text='This field use for Billing only', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='token',
            field=models.TextField(blank=True, default=None, help_text='This field use for Billing only', null=True),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='username',
            field=models.CharField(blank=True, help_text='This field use for Billing only', max_length=255, null=True),
        ),
    ]
