# Generated by Django 2.2.3 on 2020-08-20 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0006_auto_20200820_0731'),
        ('projects', '0007_add_valid_project_validation_on_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_centers', models.ManyToManyField(blank=True, related_name='reviewer_set', related_query_name='reviewer', to='projects.DataCenter', verbose_name='data_centers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(editable=False, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.Reviewer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='tickets.Ticket')),
            ],
        ),
    ]
