# Generated by Django 2.2.3 on 2020-08-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_is_reject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'get_latest_by': ['requested_at']},
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.Reviewer'),
        ),
    ]
