# Generated by Django 2.2.3 on 2020-09-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200821_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='data_centers',
        ),
    ]
