# Generated by Django 2.2.3 on 2021-08-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_reviewer_data_centers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Roll back reviewed',
                'verbose_name_plural': 'Roll back reviewed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
    ]
