# Generated by Django 2.2.3 on 2019-12-10 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=255)),
                ("sequence", models.IntegerField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[("manual", "manual"), ("script", "script")],
                        max_length=255,
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(editable=False, null=True)),
                ("finish_time", models.DateTimeField(editable=False, null=True)),
                ("is_success", models.NullBooleanField()),
                (
                    "result",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "result",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_flag", models.BooleanField(default=True)),
                ("resource_type", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("task_sequence", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("script_name", models.TextField(blank=True)),
                ("script_variables", models.TextField(default=dict)),
            ],
            options={"abstract": False},
        ),
    ]
