# Generated by Django 2.2.3 on 2019-12-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0002_add_audit_fields")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="acknowledge_id",
            field=models.IntegerField(null=True),
        )
    ]
