# Generated by Django 2.2.3 on 2019-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0003_task_acknowledge_id")]

    operations = [
        migrations.AlterField(
            model_name="task", name="finish_time", field=models.DateTimeField(null=True)
        ),
        migrations.AlterField(
            model_name="task", name="start_time", field=models.DateTimeField(null=True)
        ),
    ]
