# Generated by Django 2.2.3 on 2020-01-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0004_auto_20191218_0920")]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="overdue_alerted_at",
            field=models.DateTimeField(null=True),
        )
    ]
