# Generated by Django 2.2.3 on 2020-08-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_assignment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
