# Generated by Django 2.2.3 on 2020-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200821_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='note',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
