# Generated by Django 2.2.3 on 2020-08-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200824_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
