# Generated by Django 2.2.3 on 2021-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200824_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
