# Generated by Django 2.2.3 on 2019-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("sender", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("template_name", models.CharField(max_length=100, null=True)),
                ("template_context", models.TextField(null=True)),
                ("content", models.CharField(max_length=255, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_error", models.BooleanField(default=False)),
                ("error_msg", models.CharField(max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempts", models.IntegerField(default=0)),
            ],
        )
    ]
