# Generated by Django 2.2.3 on 2020-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100, unique=True)),
                ("signal_name", models.CharField(max_length=255)),
                ("recipient", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
