# Generated by Django 2.2.3 on 2020-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_mailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailmessage", name="content", field=models.TextField(null=True),
        ),
    ]
