# Generated by Django 2.2.3 on 2019-12-16 08:08

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Let the team know what is this price for.', max_length=255)),
                ('resource_type', models.CharField(choices=[('Virtual machine', 'vm'), ('Openshift project', 'container-cluster')], max_length=255)),
                ('matching_attrs', django.contrib.postgres.fields.jsonb.JSONField(help_text='Pairs of attribute & value matching here will enable this price string.', verbose_name='Matching attributes')),
                ('effect_attrs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Attributes that will be included calculation of this record.', size=5, verbose_name='Effect attributes')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Unit price in monthly basis.', max_digits=10)),
            ],
        ),
    ]
