# Generated by Django 2.2.3 on 2019-12-17 09:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pricing", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="pricesetting",
            name="effect_attrs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                help_text="Value of attributes will be quantity of pricing. Leave blank will apply quantity as '1'.",
                size=5,
                verbose_name="Effect attributes",
            ),
        ),
        migrations.AlterField(
            model_name="pricesetting",
            name="matching_attrs",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text=(
                    "Pairs of attribute & value matching here will enable this price string. "
                    + "Fill 'null' will apply to all resources."
                ),
                null=True,
                verbose_name="Matching attributes",
            ),
        ),
        migrations.AlterField(
            model_name="pricesetting",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("vm", "Virtual machine"),
                    ("container-cluster", "Openshift project"),
                ],
                max_length=255,
            ),
        ),
    ]
