# Generated by Django 2.2.3 on 2020-04-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_fields_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Unit price in daily basis.', max_digits=10),
        ),
    ]
