# Generated by Django 2.2.3 on 2020-08-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
        ('pricing', '0003_correct_help_text_of_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesetting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorys.Category'),
        ),
    ]
