# Generated by Django 2.2.3 on 2020-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_pricesetting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesetting',
            name='display',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
