# Generated by Django 2.2.3 on 2020-11-19 15:50

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_auto_20200923_0602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0005_pricesetting_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSettingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_type', models.CharField(blank=True, choices=[('vm', 'Virtual machine'), ('container-cluster', 'Openshift project')], max_length=255, null=True)),
                ('matching_attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('effect_attrs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=5)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('display', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorys.Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
