# Generated by Django 2.2.3 on 2020-11-23 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_pricesettinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesetting',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricesettinghistory',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
