# Generated by Django 2.2.3 on 2020-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20201123_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='effective_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricesettinghistory',
            name='effective_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
