# Generated by Django 2.2.3 on 2020-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_auto_20201123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='effective_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pricesettinghistory',
            name='effective_date',
            field=models.DateTimeField(),
        ),
    ]
