# Generated by Django 2.2.3 on 2021-01-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20201123_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesetting',
            name='effective',
            field=models.CharField(choices=[('ALWAYS', 'always'), ('PER_USE', 'per use')], default='ALWAYS', max_length=255),
        ),
    ]
