# Generated by Django 2.2.3 on 2021-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_pricesetting_effective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='effective_date',
            field=models.DateTimeField(help_text='เวลาที่แสดงเป็น UTC timezone'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, help_text='Unit price in hourly basis.', max_digits=10),
        ),
    ]
