{{- if .Values.route.enabled }}
{{- range .Values.route.routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ include "kibana.fullname" $ }}-{{ .name }}"
  labels:
    app: {{ include "kibana.name" $ }}
    helm.sh/chart: {{ include "kibana.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations: 
    haproxy.router.openshift.io/timeout: {{ .haproxytimeout | default "60s" | quote }}
{{- with .spec }}
spec:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}