# Generated by Django 2.2.3 on 2020-01-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_add_audit_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketitem",
            name="estimated_price",
            field=models.DecimalField(decimal_places=6, max_digits=19, null=True),
        ),
    ]
