# Generated by Django 2.2.3 on 2020-01-30 08:05

import cloudform.tickets.models.ticket
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketitem_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='projects.Application', validators=[cloudform.tickets.models.ticket.validate_only_active]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='note_from_operator',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
