# Generated by Django 2.2.3 on 2020-08-14 06:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='price_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
