# Generated by Django 2.2.3 on 2020-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketitem_price_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('reviewer_commented', 'Reviewer Commented'), ('feedback_applied', 'Feedback Applied'), ('reviwer_rejected', 'Reviewer Rejected'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='created', max_length=255),
        ),
    ]
