# Generated by Django 2.2.3 on 2020-08-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200820_0731'),
        ('tickets', '0007_auto_20200824_0300'),
    ]

    operations = [
    ]
