# Generated by Django 2.2.3 on 2020-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_merge_20200827_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('commented', 'Commented'), ('feedback_applied', 'Feedback Applied'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='created', max_length=255),
        ),
    ]
