# Generated by Django 2.2.3 on 2020-09-08 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200904_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvement',
            name='approver_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
