# Generated by Django 2.2.3 on 2020-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_approvement_approver_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPTTApprove',
            fields=[
            ],
            options={
                'verbose_name': 'Non-PTT Approver',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.approver',),
        ),
    ]
