serviceAccountName: dcloud

securityContext:
  runAsUser: 1001

replicaCount: 5

image:
  repository: dcloudnexus-registry.pttdigital.com/dcloud/dcloud
  tag: production-v0.0.4
  pullPolicy: Always

imagePullSecrets:
  - name: registry-irrnexus-cred

strategy:
  type: Recreate
  rollingUpdate: null

command:
  - celery
  - -A
  - cloudform
  - worker
  - --loglevel=INFO
  - --max-tasks-per-child=8
  - --max-memory-per-child=12000

nameOverride: dcloud-prd-celery-worker
fullnameOverride: dcloud-prd-celery-worker

env:
  - name: DCLOUD_VERSION
    value: "undefined"
  - name: DCLOUD_GIT_HASH
    value: "undefined"
  - name: DCLOUD_DEPLOY_DATE
    value: "undefined"
  - name: AWX_API_HOST
    value: "https://dcloudawx.pttdigital.com"
  - name: POSTGRES_DB
    value: dcloud
  - name: POSTGRES_USER
    value: dcloudadmin
  - name: POSTGRES_HOST
    value: 10.224.65.107
  - name: DCLOUD_FORCE_SECURE_REQUEST
    value: true
  - name: EMAIL_ENABLED
    value: true
  - name: EMAIL_BACKEND
    value: "smtp"
  - name: EMAIL_HOST
    value: "app2smtp.pttgrp.corp"
  - name: EMAIL_PORT
    value: "25"
  - name: EMAIL_HOST_USER
    value: ""
  - name: EMAIL_HOST_PASSWORD
    value: ""
  - name: SENDMAIL_SENDER
    value: pttdigital-cloudadmin@pttdigital.com
  - name: REDIS_ENABLED
    value: true
  - name: REDIS_HOSTS
    value: "dcloud-production-app-redis-master"
  - name: REDIS_URL
    value: "redis://dcloud-production-app-redis-master:6379"
  - name: GRAYLOG_HOST
    value: "dcloudgraylog.pttdigital.com"
  - name: GRAYLOG_HANDLER_CLASS
    value: "graypy.handler.GELFTCPHandler"
  - name: ELASTICSEARCH_HOST
    value: "dcloud-prd-elasticsearch"
  - name: ELASTICSEARCH_PORT
    value: "9200"
  - name: API_URL
    value: "http://dcloud-prd-app:8000"
  - name: VCENTER_URL
    value: "https://grp-cfvc-p01.pttgrp.corp"
  - name: TZ
    value: 'Asia/Bangkok'

envFrom:
  - secret:
      name: dcloud-psql
  - secret:
      name: dcloud-prd-awx-automation
  - secret:
      name: dcloud-secret-key
  - secret:
      name: dcloud-celery

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 200m
    memory: 256Mi

healthCheck:
  enabled: true
  readinessProbe: null
  livenessProbe:
    exec:
      command:
        - sh
        - '-c'
        - celery inspect ping -A cloudform -d celery@$HOSTNAME || exit 1
    initialDelaySeconds: 5
    timeoutSeconds: 60
    periodSeconds: 300
    successThreshold: 1
    failureThreshold: 3
