serviceAccountName: dcloud

securityContext:
  runAsUser: 1001

replicaCount: 1

image:
  repository: registry.dclouddev.opsta.in.th/dcloud/nginx
  tag: 1.16.1
  pullPolicy: Always

imagePullSecrets:
  - name: registry-irrnexus-cred

nameOverride: dcloud-dev-docs-nginx
fullnameOverride: dcloud-dev-docs-nginx

volumeMounts:
  - name: dcloud-dev-docs-static-volume
    mountPath: /code/static
  - name: dcloud-dev-docs-media-volume
    mountPath: /code/media

volumes:
  - name: dcloud-dev-docs-static-volume
    persistentVolumeClaim:
      claimName: dcloud-dev-docs-static-volume-storage
  - name: dcloud-dev-docs-media-volume
    persistentVolumeClaim:
      claimName: dcloud-dev-docs-media-volume-storage

env:
  - name: PREFIX_PATH
    value: "/docs"
  - name: DOCS_HOST
    value: dcloud-dev-docs
  - name: DOCS_PORT
    value: 8000
  - name: TZ
    value: 'Asia/Bangkok'

containerPorts:
  - 8000

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 1Gi

service:
  enabled: true
  type: ClusterIP
  annotation: {}
  ports:
    - name: app-svc
      protocol: TCP
      externalPort: 8000
      internalPort: 8000

# route:
#   enabled: true
#   routes:
#     - name: dcloud-dev-docs-route
#       spec:
#         host: dcloud-dev.pttdigital.com
#         path: /docs
#         to:
#           kind: Service
#           name: dcloud-dev-docs-nginx
#           weight: 100
#         port:
#           targetPort: app-svc
#         wildcardPolicy: None
        # tls:
        #   termination: edge
        #   certificate: "CHANGEME"
        #   key: |
        #     CHANGEME
        #   caCertificate: |
        #     CHANGEME
        #   insecureEdgeTerminationPolicy: Redirect

# healthCheck:
#   enabled: false
#   readinessProbe:
#     httpGet:
#       path: /ready
#       port: 80
#     initialDelaySeconds: 0
#     timeoutSeconds: 1
#     periodSeconds: 10
#     successThreshold: 1
#     failureThreshold: 3
#   livenessProbe:
#     httpGet:
#       path: /health
#       port: 80
#     initialDelaySeconds: 0
#     timeoutSeconds: 1
#     periodSeconds: 10
#     successThreshold: 1
#     failureThreshold: 3
