# Generated by Django 2.2.3 on 2020-11-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_auto_20200923_0602'),
    ]

    operations = [
    ]
