# Generated by Django 2.2.3 on 2020-02-04 07:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(max_length=255)),
                ("field", models.CharField(max_length=255)),
                ("sequence", models.IntegerField()),
                (
                    "value",
                    models.CharField(
                        help_text="Actual value that will be used in script or calculation.",
                        max_length=255,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="Display value that will appear to user.",
                        max_length=255,
                    ),
                ),
                (
                    "extra_fields",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        blank=True,
                        help_text="Side effect when user select this value.",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="formconfig",
            index=models.Index(fields=["page"], name="form_config_page_index"),
        ),
        migrations.AddIndex(
            model_name="formconfig",
            index=models.Index(
                fields=["page", "field"], name="form_config_page_field_index"
            ),
        ),
    ]
